### ISSUE TITLE
Missing dock icon for the security center

### ISSUE THREAD

**Issue by local-optimum** [canonical/desktop-security-center#50]
Dock icon is not present, but is in the GNOME activity view

**Comment by juanruitina** [comment]
Some more feedback for the Security Center (adding it here by @d-loose's suggestion):

- [ ] Add links for feedback (see [UDENG-3896](https://warthogs.atlassian.net/browse/UDENG-3896)). Let's also update the "Learn more" link as soon as the Discourse post is published.
- [ ] Show "Home folder" in the initial page even if there are no rules yet. It immediately gives users an indication of which interfaces can be managed from the Security Center. It can look like this:

![ac2](https://github.com/user-attachments/assets/e76c4b7b-8733-4116-81a2-87d94b097cc3)

I'm also opened one issue in the prompting repo for the options in the prompts: https://github.com/canonical/prompting-client/issues/82

**Comment by d-loose** [comment]
(almost) fixed by #52 and #56.
Still waiting for one missing URL before updating the links.

**Comment by sminez** [comment]
@d-loose I think we can close this one now?

**Comment by d-loose** [comment]
Fixed by #59
