### ISSUE TITLE
Visual tweaks

### ISSUE THREAD

**Issue by juanruitina** [canonical/desktop-security-center#53]
Besides the functional feedback in https://github.com/canonical/desktop-security-center/issues/50, there are some bits that are perhaps less of a priority but that need tweaking on the visual side:

- [x] Hover state on the switch container: background should change for the whole thing, it looks weird now that there are those narrow bars above and below that remain white:

<img width="567" alt="Screenshot 2024-09-03 at 10 44 10" src="https://github.com/user-attachments/assets/ba5a7813-1497-4a50-a8b0-84aa10ea7d7f">

- [ ] When changing pages, animation is the default (sliding up). Sliding left/right would be more intuitive, see for instance Settings app › Displays › Night Light.
- [x] Responsiveness isn't great, window breaks when reducing the size of the window, content disappearing and then the spinner showing indefinitely (this is also a functional bug, but whatevs)

<img width="605" alt="Screenshot 2024-09-03 at 10 59 53" src="https://github.com/user-attachments/assets/9fc2060a-ab23-4d93-bd92-1707356a3d44">

Same as with prompts, the sizing of text is inconsistent: paragraphs, buttons, switches... seem to have the same size in GNOME apps like Settings, and I don't think this should be much different. But this doesn't look egregious, so let me figure this out before we make any further changes.

**Comment by d-loose** [comment]
Fixed by #58, animation issue tracked by UDENG-4455
