### ISSUE TITLE
Update "Require apps" switch label

### ISSUE THREAD

**Issue by juanruitina** [canonical/desktop-security-center#60]
Tweak "Require snaps to ask for system permissions" switch label so it reads "Require apps to ask for system permissions" instead [as per the designs](https://www.figma.com/design/fSuEb6YSUBewbOMeqE3v8s/Security-Center?node-id=1109-5172&node-type=canvas&t=PPjH4tt6Kjmqg04S-0).

![ac2](https://github.com/user-attachments/assets/9405f347-f1db-4346-9080-ce7872557d6d)

**Comment by sminez** [comment]
We need to get the Jira workflow set up here so we can pull things through when they are raised from GitHub. In the meantime, @juanruitina would you mind also raising this as a ticket in Jira so we can track it?
