### ISSUE TITLE
cant download anything on firefox, i tried allowing only the folder, only the file all options and in firefox download page says failed to everything i try to download

### ISSUE THREAD

**Issue by alisson3000br** [canonical/desktop-security-center#70]
i deleted all the rules and tried again but it is obviously nor working properly

**Comment by sminez** [comment]
Please can you provide the details asked for in the [bug report](https://github.com/canonical/desktop-security-center/issues/new?assignees=sminez%2Cjuanruitina&labels=bug%2Cprompting&projects=&template=bug_report_prompts.yml) template so we can look into this? If you can you also provide the output of `snap info` for the following snaps that would really helpful:
- snapd
- desktop-security-center
- prompting-client

If possible can you also share the details of the file you are trying to download from Firefox? We have seen a couple of instances of this behaviour previously that are related to a kernel issue which there is a fix coming from, so it would be useful to know if this is the same thing or something new.

cc @olivercalder I think you know the status of the fix in question? I'll ping JJ in mattermost as I'm not sure of his GitHub username

**Comment by olivercalder** [comment]
Just to clarify, after you deleted all the rules and tried again, did the download then succeed?

If not, as @sminez mentioned, there is a known bug with prompting when one tries to download a very large file via firefox, which relies on `.part` files. This could be when downloading a file from Google Drive, Proton Drive, or downloading an ISO from ubuntu.com, for example. In these cases, the kernel blocks writing to one of the part files and the download fails, even if there's an allow rule or you reply with an allow. However, this bug should *not* occur when downloading files outside of circumstances like these. For example, when right clicking an image to "Save Image As...". Please let us know whether the download failed in a circumstance like the one mentioned above. There's a fix for this bug, which I can describe if needed.

**Comment by alisson3000br** [comment]
i'm kind of busy theses days, anything that i try to download will prompt and i tried all the option available, if i download a jpeg it prompts 5 times i have to allow 5 times and even if the rules are stored i keeps prompting everything i try to download

**Comment by alisson3000br** [comment]
the always allow option for the selected folder does not work, it will always keep prompting
