### ISSUE TITLE
list all (manually) installed packages and switch their status or show their problem

### ISSUE THREAD

**Issue by hifron** [canonical/desktop-security-center#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution/feature you'd like.

`apt-mark showmanual`
list all packages installed and marked as manually installed

1. make it possible to switch their status to automatically installed
2. show what they are about in few sentences or secondary view
3. list packages with higher priorities than default ones(it is apt feature), but it could be also third party sources like Microsoft one(it could even be MS SQL database, not only MS Edge, MS Code or Google Chrome :)
4. list all packages without repo like locally installed ones, like with _apt install ./package_ or _dpkg -i package && apt install_
5. list all packages(or devices) under regulations or in restricted usage like RDS(now also in v4l-utils), could be seen in packages.ubuntu.com in package list
6. packages could be also selected via apt list, or **apt search term|grep installed** :)

### Describe any alternatives you've considered.

3.) apt preferences in /etc/apt could setup it, but some UI is probably missing although it is more advanced feature, but also security related

maybe some corporate policies could be also applied(including EntraID) or remote system administration with massive maintenance, but country regulations are also in place, not only user or admin choice...

**Comment by hifron** [comment]
`sudo apt-mark auto libqt*` :)

**Comment by hifron** [comment]
but beware before `sudo apt autopurge` , coincidence is not an option

**Comment by sminez** [comment]
Hi @hifron, I'm afraid what you are asking for here is not within the scope of this application: the security center is not responsible for any aspects of package management.
